### ISSUE TITLE
RuntimeError: only batches of spatial targets supported (3D tensors) but got targets of dimension: 4

### ISSUE THREAD

**Issue by GeneralJing** [SforAiDl/KD_Lib#122]
Traceback (most recent call last):
  File "tools/train_kd_lib.py", line 98, in <module>
    distiller.train_teacher(epochs=5, plot_losses=True, save_model=True)    # Train the teacher network
  File "/home/xxx/anaconda3/envs/tp/lib/python3.8/site-packages/KD_Lib/KD/common/base_class.py", line 119, in train_teacher
    loss = self.ce_fn(out, label)
  File "/home/xxx/anaconda3/envs/tp/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/xxx/anaconda3/envs/tp/lib/python3.8/site-packages/torch/nn/modules/loss.py", line 1047, in forward
    return F.cross_entropy(input, target, weight=self.weight,
  File "/home/xxx/anaconda3/envs/tp/lib/python3.8/site-packages/torch/nn/functional.py", line 2693, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "/home/xxx/anaconda3/envs/tp/lib/python3.8/site-packages/torch/nn/functional.py", line 2390, in nll_loss
    ret = torch._C._nn.nll_loss2d(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
RuntimeError: only batches of spatial targets supported (3D tensors) but got targets of dimension: 4

**Comment by GeneralJing** [comment]
You mean the current implementation just for classification net? The net that i used is a segmentation network, bisenetv2.

**Comment by Het-Shah** [comment]
Yes, the current implementation is just for classification. You will have to modify parts of the library for segmentation.

**Comment by GeneralJing** [comment]
all right. thank you for your reply.

**Comment by Het-Shah** [comment]
Closing the issue. Feel free to reopen/open a new issue if you need any help :)
